### ISSUE TITLE
URL app cloud

### ISSUE THREAD

**Issue by josecastillolema** [jeanvillete/fiap-stock-ecommerce#19]
Olá Jean!

não consegui achar a url da app, consegue me passar por favor!

Obgdo

**Comment by jeanvillete** [comment]
Olá José, boa noite.

Desculpe a demora em responder,

A URL das duas pontas (Frontends);
- ec2-3-84-198-88.compute-1.amazonaws.com:3131/
- ec2-3-84-198-88.compute-1.amazonaws.com:3232/

Lembrando que a topologia da aplicação está no repositório do github, e o que contribui com o repositório referente a sua matéria está no; https://github.com/jeanvillete/fiap-stock-ecommerce/tree/master/aws-infra-as-code

Eu tive que deployar em uma instância consumindo os créditos de outra matéria, pois os da sua matéria já expiraram, por isto não tinha a URL.

Obrigadão,

Abraços,
